### PR TITLE
Fix #1: Add tests from examples folder using VisualRegressionTests.jl

### LINKED ISSUE #1: Translate "examples" folder to tests using VisualRegressionTests.jl
@darsnack 
Hello, I would like to contribute to the repo through above project. It is my understanding that for the above project, we will have reference images stored in a separate repo and during testing, the test function will clone the repo and use those reference files for VisualRegressionTests.jl

Is this approach correct?

### PR DESCRIPTION
**Pull request by Diaga**
Fixes #1 .

- [x] Setup runtests file.
- [x] Translate tests from "examples" folder 
- [x] Review approved

The tests have been written, however, they fail if Julia is restarted. Maybe this is something to do with the random seed generation?

### CODE REVIEW

**Comment by Diaga** [comment]
A few best practices questions:

1. How to name testsets?
2. Should we have a separate "testset" for each file or does @plottest macro work for files with only a single test?
3. Is there a linter for this repo or Julia in general?
4. There were files with multiple plots. I am unsure if creating a testset and running plottest separately is the best way.

File: test/lif-test.jl [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+    @time output = simulate!(lif, T; cb = record)
+
+    # plot sparse voltage recording
+    voltage_plot = plot!(spikes, voltages,
+        title = "LIF Membrane Potential Over Time", xlabel = "Time (sec)", ylabel = "Potential (V)", label = "Sparse (default)")
+
+    # plot raster plot
+    raster_plot = rasterplot(spikes, output, label = ["Input", "Output"], title = "Raster Plot", xlabel = "Time (sec)")
+
+    @plottest plot(raster_plot, voltage_plot, layout = grid(2, 1)) joinpath(datadir, "LifTestSparse.png") !istravis
```
Comment (darsnack) [inline test/lif-test.jl]: This is actually not multiple plots. The prior plot commands generate subplots, and this line plots everything in a single window. So you only want to save the plot resulting from this last line.

File: test/population-test.jl [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+        for id in 1:size(pop)
+            push!(voltages[id], getvoltage(pop[id]))
+        end
+    end
+    @time outputs = simulate!(pop, T; cb = cb, inputs = [n1synapse, n2synapse, (t; dt) -> 0])
+
+    rasterplot(outputs, label = ["Input 1", "Input 2", "Inhibitor"])
+    title!("Raster Plot")
+    xlabel!("Time (sec)")
+end joinpath(datadir, "PopulationTest.png") !istravis
```
Comment (darsnack) [inline test/population-test.jl]: We can actually name this "Winner-Take-All Test" to be more informative.

File: test/srm0-test.jl [hunk 3]
```diff
@@ -0,0 +1,48 @@
...
+    srm = Neuron(QueuedSynapse(Synapse.EPSP(ϵ₀ = 2, τm = 0.5, τs = 1)), SRM0(η₀, τᵣ), Threshold.Ideal(vth))
+    excite!(srm, spikes)
+    @time simulate!(srm, n; dt = ∂t, cb = record, dense = true)
+
+    # plot voltages with response function
+    voltage_plot = plot!(∂t .* collect(1:n), voltages, label = "EPSP response")
+    xlims!(0, T)
+
+    @plottest plot(raster_plot, voltage_plot, layout = grid(2, 1)) joinpath(datadir, "Srm0TestResponse.png") !istravis
+    xticks!(0:T)
```
Comment (darsnack) [inline test/srm0-test.jl]: Same as before, we only need to save the last plot command's image.

File: test/srm0-threshold-test.jl [hunk 4]
```diff
@@ -0,0 +1,46 @@
...
+    srm = Neuron(QueuedSynapse(Synapse.Alpha()), SRM0(η₀, τᵣ), Threshold.Poisson(5.0, 0.5, 0.1))
+    voltages = Float64[]
+    excite!(srm, spikes)
+    @time simulate!(srm, n; dt = ∂t, cb = record, dense = true)
+
+    # plot voltages with response function
+    voltage_plot = plot!(∂t .* collect(1:n), voltages, label = "\\alpha response")
+    xlims!(0, T)
+
+    @plottest plot(raster_plot, voltage_plot, layout = grid(2, 1), xticks = 0:T) joinpath(datadir, "Srm0ThresholdTestResponse.png") !istravis
```
Comment (darsnack) [inline test/srm0-threshold-test.jl]: Same, last plot command.

File: test/lif-test.jl [hunk 5]
```diff
@@ -0,0 +1,50 @@
+@testset "lif-test.jl" begin
```
Comment (darsnack) [inline test/lif-test.jl]: No need to create a new `@testset`. See the comment about multiple plot commands. All of this code will produce a single plot, so it can be wrapped in a single `@plottest` command (similar to the excite test). The plot is built iteratively using multiple plot commands, but in the end there will only be a single plot.

**Review by darsnack — CHANGES_REQUESTED** [review]
Good job! There are a couple issues with the PNGs. There don't appear to be correct; the plot is half cut off. Let me investigate this issue.

To answer your questions:
1. Use something informative. So the test set "SpikingNN.jl" would probably be called "Visual Tests" long term. For now it doesn't matter since we only have the one test set.
2. Not sure exactly what the questions is, but `@plottest` is equivalent to `@assert`. So there can be multiple `@plottest` calls within a single test set. This is effectively what you are doing with your loop in `runtests.jl`. A single test set called "SpikingNN.jl" with multiple calls to `@plottest` within the loop.
3. There is no linter for this repo. There is [this guide](https://docs.julialang.org/en/v1/manual/style-guide/), and I think VS Code has a linter. There is also [this package](https://github.com/tonyhffong/Lint.jl). I don't use a linter, so your best bet at an answer is to ask on [the Julia Slack group](https://slackinvite.julialang.org/).
4. Added some comments in the review that should resolve this. There is no need to create a new test set.

**Comment by Diaga** [comment]
Updated PR with changes required. However, there are still two issues.
1. ~~Mentioned in #3 about missing test dependencies~~ Fixed and tested.
2. The other is the issues with PNG. There is a warning that might help:
```
GKS: Rectangle definition is invalid in routine SET_WINDOW
```

**Comment by darsnack** [comment]
Let me look into the PNG issue. Something related to GR being updated I think.

**Comment by darsnack** [comment]
Seems to be an issue with GR. I switched those two examples to use PyPlot. Can you rebase from upstream and try regenerating the PNGs?

**Comment by darsnack** [comment]
Can you rebase one more time? I added some missing test dependencies. I want to see if the tests pass on the CI (which should also work now). If they do, then we can merge.

**Comment by Diaga** [comment]
SpikingNN is using Github WorkFlows while I added the travis detection to check if we want to display windows if tests fail. Switching to WorkFlows detection.

File: test/srm0-test.jl [hunk 6]
```diff
@@ -0,0 +1,49 @@
+@plottest begin
```
Comment (darsnack) [inline test/srm0-test.jl]: Can you change to `@test_skip @plottest`? Currently, PyPlot is causing CI issues, but I'd rather merge the working code than worry about that. Since we'll eventually move back to GR.

File: test/srm0-threshold-test.jl [hunk 7]
```diff
@@ -0,0 +1,47 @@
+@plottest begin
```
Comment (darsnack) [inline test/srm0-threshold-test.jl]: Same for this test.

File: test/runtests.jl [hunk 8]
```diff
@@ -1,6 +1,30 @@
...
+    "lif-test.jl",
+    "population-test.jl",
+    "srm0-test.jl",
+    "srm0-threshold-test.jl",
+    "stdp-test.jl"
+]
+
 @testset "SpikingNN.jl" begin
-    # Write your tests here.
+    for testfile in testfiles
```
Comment (darsnack) [inline test/runtests.jl:28]: Can you add the environment variable for GR as described [here](https://github.com/jheinen/GR.jl/issues/278#issuecomment-563129986)

**Review by darsnack — CHANGES_REQUESTED** [review]
A couple of small changes, and then we can merge. Currently, some tests do fail, but I want merge anyways. I'll investigate the failing tests, but it is likely due to the RNG issue.

**Review by darsnack — APPROVED** [review]
Great let’s merge!
